### PR TITLE
If iterm exists, ask user when launching Docker Quickstart Terminal

### PR DESCRIPTION
**Pull request by virajkanwade**

### CODE REVIEW

**Comment by jeffdm** [comment]
Thanks for the PR!

Please sign your commit. This should do it:

```
$ git commit --amend -s --no-edit
$ git push -f
```

Taking a look, but I do think there's a way to auto detect this. See https://github.com/kitematic/kitematic/blob/master/resources/terminal for an example.

**Comment by jeffdm** [comment]
By the way, this change is great. I've ran into quite a few people wanting iTerm support.

**Comment by virajkanwade** [comment]
Thanks Jeff.

Yes we could move to something like your example, but I personally prefer having the control over it. We could add "Don't ask me again" or "Make default" options if possible.

The main.scpt auto detects with 'tell application "Finder" to get application file id "com.googlecode.iterm2"'. It asks user only if iterm exists. I think the osascript approach opens iterm while checking for it. Since my approach asks user if Terminal or iTerm, starting iTerm when the user wants and selects Terminal didn't seem right.

Hope this explains.
Regards,
Viraj

**Comment by virajkanwade** [comment]
https://github.com/docker/toolbox/pull/122

**Pull request closed without merging**
