### PR TITLE
Virtual box to v5.0.6

### PR DESCRIPTION
**Pull request by gmanfunky**
Virtual box v5.0.6 was just released which includes a significant fix for Windows Host<->Guest network problems. 

https://www.virtualbox.org/wiki/Changelog

I needed this update today when my host mysteriously stopped being able to talk to the boot2docker guests using host-only network adapters.

### CODE REVIEW

**Comment by mchiang0610** [comment]
@gmanfunky Thanks for this.

**Comment by jeffdm** [comment]
LGTM

Can you sign your commit? For ex:

```
$ git commit --amend -s --no-edit
$ git push -f
```

Thanks!

**Comment by gmanfunky** [comment]
Signed off per https://github.com/docker/docker/blob/master/CONTRIBUTING.md#sign-your-work

**Comment by thaJeztah** [comment]
Sign-off looks good, thanks @gmanfunky !

**Comment by jeffdm** [comment]
Thanks so much @gmanfunky!

@thaJeztah review much appreciated :smile:

**Pull request merged**
