### PR TITLE
Use users default shell instead of bash

### PR DESCRIPTION
**Pull request by virajkanwade**
Signed-off-by: Viraj Kanwade <github@virajk.otherinbox.com>

### CODE REVIEW

**Comment by jeffdm** [comment]
Great! Thanks for this!

I think we need to change `start.sh` to remove `--shell=bash` near the end. Otherwise, this LGTM

**Comment by virajkanwade** [comment]
@jeffdm done.

**Comment by jeffdm** [comment]
LGTM!

**Comment by jeffdm** [comment]
Thanks @virajkanwade !

**Pull request merged**
