### PR TITLE
clear all_proxy if not socks address

### PR DESCRIPTION
**Pull request by bbodenmiller**
Fixes https://github.com/docker/toolbox/issues/539. Workaround for https://github.com/docker/docker/issues/25740 & https://github.com/golang/go/issues/16715.

### CODE REVIEW

**Comment by bbodenmiller** [comment]
@nathanleclaire any thoughts on this one? Docker Toolbox would not run without it for me.

**Comment by nathanleclaire** [comment]
Interesting, can you indicate which protocol it _is_ set to in your case?

**Comment by bbodenmiller** [comment]
Yes, in my case `ALL_PROXY` is set to `http://www-proxy.company.com:31060`. I'm not sure it has a purpose but either way it is set on my company machine. Without this patch I get the error `proxy: unknown scheme: http` same as https://github.com/docker/toolbox/issues/539.

**Comment by nathanleclaire** [comment]
rough.  LGTM

**Comment by bbodenmiller** [comment]
Thanks for the merge. More supporting details: https://curl.haxx.se/docs/manpage.html

> ALL_PROXY [protocol://]<host>[:port]

>> Sets the proxy server to use if no protocol-specific proxy is set.

**Comment by nathanleclaire** [comment]
fyi, just released 1.12.1 toolbox with these recent fixes you've gotten merged !

**Comment by bbodenmiller** [comment]
Sweet, thanks!

**Pull request merged**
