### PR TITLE
improve proxy variables check

### PR DESCRIPTION
**Pull request by bbodenmiller**
* Fix `if` statements - based on my tests and https://stackoverflow.com/questions/3869072/test-for-non-zero-length-string-in-bash-n-var-or-var the current method will always return true even if `PROXY` environment variables are not set
  * Improves on https://github.com/docker/toolbox/pull/183
* Replace inconsistent tabs in `start.sh` with spaces like exists elsewhere in `start.sh`

### CODE REVIEW

**Comment by nathanleclaire** [comment]
Have you run through this end-to-end to verify that the created VM has the proper settings?

**Comment by bbodenmiller** [comment]
I've run through it end-to-end in that when I don't set a proxy via `--engine-env` my Docker does not work. Also here is the contents of `/var/lib/boot2docker/profile` after running this:



I've also tested `docker run hello-world` and it successfully downloads via my proxy.

Any other tests you'd like me to run through?

Worth noting tests were done with https://github.com/docker/toolbox/pull/553 & https://github.com/docker/toolbox/pull/552 also applied as I had failures without them.

**Comment by nathanleclaire** [comment]
Thanks, just making sure... LGTM

**Pull request merged**
