### PR TITLE
Fail fast in case we are run without a terminal

### PR DESCRIPTION
**Pull request by sirkkalap**

### CODE REVIEW

**Comment by jeffdm** [comment]
LGTM

Can you please sign your commit before merging:

```
$ git commit --amend -s --no-edit
$ git push -f
```

**Comment by sirkkalap** [comment]
Done that. Should I make a new PR or will this suffice?

**Comment by sirkkalap** [comment]
@jeffdm anything else I could do at this point?

**Comment by jeffdm** [comment]
Perfect, sorry for the delay. Merging

**Pull request merged**
