### PR TITLE
Optional box name argument for start.sh in Windows

### PR DESCRIPTION
**Pull request by kramos**
Allowing you to optionally pass in a machine name and use this for more than just boxes called default (in Windows).  The script is too useful to use only once!

### CODE REVIEW

**Comment by nathanleclaire** [comment]
How about something like an environment variable instead?  e.g. `DOCKER_MACHINE_NAME`

**Comment by kramos** [comment]
Sounds fine to me. Would you like me to make that update and test it?

**Comment by nathanleclaire** [comment]
Sounds good to me!

**Comment by kramos** [comment]
Updated and tested.

**Comment by nathanleclaire** [comment]
Looks like quite a few commits in there -- can you please use `git rebase -i HEAD~6` (or eqiuvalent) to squash them all down into one?  Thanks

**Comment by kramos** [comment]
Will re-create

**Pull request closed without merging**
