### PR TITLE
If iterm exists, use iterm as default for “Docker Quickstart Terminal”

### PR DESCRIPTION
**Pull request by virajkanwade**
Signed-off-by: Viraj Kanwade <github@virajk.otherinbox.com>

### CODE REVIEW

**Comment by SvenDowideit** [comment]
please make sure this is tested on an osx box that doesn't have iterm installed :)

**Comment by virajkanwade** [comment]
This has already been tested on 2 different macbooks. What error are you seeing?

**Comment by jeffdm** [comment]
This is awesome! Thanks again for the PR!

Small nitpick: It seems to open two tabs when iTerm launches. Is there an easy way to make it open only one new tab?

**Comment by virajkanwade** [comment]
Unfortunately, couldn't figure that out. Many others seem to have that
problem.

**Comment by jeffdm** [comment]
Got it, thanks!

**Comment by jeffdm** [comment]
Taking a look and then let's get this merged. Thanks for the quick follow ups!

**Comment by thaJeztah** [comment]
This may need a mention in the docs too, so that people know the change in behavior.

Are there cases where people have iTerm installed but still prefer Term? (unlikely, but possible) Is there a way to override the behavior?

**Comment by virajkanwade** [comment]
Welcome to the conflict! :)
Initially i wrote the script such that it would ask.
But the overall feedback was it should auto use iterm. So had to change the
PR.

Altough i had not implemented "don't ask again" yet.

Anyways i have left the code commented in case somebody wants to overwrite
it :)

**Comment by SvenDowideit** [comment]
@virajkanwade I don't have an osx box to test with atm, but when we had iterm support PR's in the boot2docker osx-installer, they had error messages pop up when run on a box that didn't have iterm installed. - it was just a note to head this off - if you've tested it \o/

**Comment by virajkanwade** [comment]
@sven you mean other PRs?
Mine has been tested on 2 macbooks with no iterm. If my PR is also giving
errors, please do let me know.

**Comment by SvenDowideit** [comment]
https://github.com/boot2docker/osx-installer/pulls

yay for your tests :)

**Comment by SvenDowideit** [comment]
this needs a rebase though.

**Comment by jeffdm** [comment]
This was definitely on the right track. Feel free to re-open!

**Comment by virajkanwade** [comment]
https://github.com/docker/toolbox/pull/154

**Pull request closed without merging**
