### PR TITLE
fix broken links per issue #30 on docs-base-1.12-integration

### PR DESCRIPTION
**Pull request by londoncalling**
Signed-off-by: Victoria Bialas <victoria.bialas@docker.com>

### CODE REVIEW

**Comment by jeffdm** [comment]
LGTM

**Comment by SvenDowideit** [comment]
LGTM @jeffdm please merge?

**Comment by londoncalling** [comment]
@SvenDowideit are we okay with this even though the link checker failed? Is this what you were talking about?  I believe those links are properly formatted for new location of D4mac, D4win?

**Comment by SvenDowideit** [comment]
yeah, this checker can't access the non-public docker4 repo, so fails on links to it

**Comment by londoncalling** [comment]
@jeffdm neither @SvenDowideit nor I have merge perms, but this is a good commit. The link checker doesn't process the `d4mac`  and `d4win` links here properly. Can you merge for us?

**Comment by thaJeztah** [comment]
ping @jeffdm could you merge this please?

**Pull request merged**
