### PR TITLE
If iTerm exists, option for iTerm

### PR DESCRIPTION
**Pull request by virajkanwade**
Signed-off-by: Viraj Kanwade <github@virajk.otherinbox.com>

### CODE REVIEW

**Comment by virajkanwade** [comment]
A combination of both worlds.

If iTerm does not exist, default to Terminal
If iTerm exists, ask the user with an option to set default (value stored in ~/.docker/default_terminal)
If the user wants to reset default, "rm ~/.docker/default_terminal"

Also fixed iTerm 2 tabs issue

**Comment by jeffdm** [comment]
This looks great. Thanks @virajkanwade ! I know it can be tough to do this all in applescript :smiley: 

One last note: is it possible to change the `default_terminal` file location to `ls -al ~/Library/Application\ Support/DockerToolbox/` ?

**Comment by jeffdm** [comment]
One more note:

1. Can we change "Use" to "Open using:" ?

**Comment by virajkanwade** [comment]
Sure. I wasn't very sure where to put it and ~/.docker seemed to be a good option.

Will update paths to Application Support

**Comment by jeffdm** [comment]
Awesome! Thanks @virajkanwade

**Comment by virajkanwade** [comment]
Done. Please take a look.

**Comment by jeffdm** [comment]
Thanks! Looking

**Comment by jeffdm** [comment]
LGTM This is great work! Thanks @virajkanwade !

Merging.

**Comment by virajkanwade** [comment]
Phew! Finally :)

**Comment by thaJeztah** [comment]
Thanks @virajkanwade !

**Pull request merged**
