### PR TITLE
If iTerm exists, option for iTerm

### PR DESCRIPTION
**Pull request by virajkanwade**
A combination of both worlds.

If iTerm does not exist, default to Terminal
If iTerm exists, ask the user with an option to set default (value stored in ~/.docker/default_terminal)
If the user wants to reset default, "rm ~/.docker/default_terminal"

### CODE REVIEW

**Comment by virajkanwade** [comment]
Future TODO: iTerm script will have to be updated when 2.9+ comes out
https://gitlab.com/gnachman/iterm2/wikis/Applescript

**Comment by thaJeztah** [comment]
Thanks @virajkanwade! I see some commented code in these scripts; is that something you're still working on?

```AppleScript
# if not (exists window 1) or (itermRunning = false) then
# 	 reopen
# end if
```

```ActionScript
# set question to display dialog "Use Terminal or iTerm?" with title (name of current application as text) with icon note buttons {"Terminal", "iTerm", "Cancel"} default button 1
# set answer to button returned of question
```

**Comment by virajkanwade** [comment]
@thaJeztah 
#1 mistake
#2 Still trying to figure out how to come up with a better interface, hence left it as commented.
Will submit new PR removing the first comment

**Comment by virajkanwade** [comment]
https://github.com/docker/toolbox/pull/155
Hopefully, that would be the one :)

**Comment by thaJeztah** [comment]
@virajkanwade for future PRs; there's no need to close a PR; if you `git commit -s --amend`, then *force push*, github will automatically update your existing PR.

It's important that you keep the PR *open*, because Github does not update closed PRs

**Comment by virajkanwade** [comment]
Hi Sebastiaan,

On one of my other projects that didnt work. The pr was merged but my code
was nowhere to be found. Hence closed the pr and created new.

Maybe i was doing something wrong. Will try that next time.

Thanks
Viraj

**Comment by thaJeztah** [comment]
No problem, just try it next time and if it *doesn't* work, you can always open a new one :smile: 

I must admit, it's a bit harder to check with these .scpt files, because you cannot see the code-changes on GitHub..

**Comment by virajkanwade** [comment]
Yeah, lets add a project for github plugin to diff scpt files :)

**Comment by virajkanwade** [comment]
@thaJeztah  please take a look at #156

**Comment by thaJeztah** [comment]
ah, nice one, didn't know that :-)

**Pull request closed without merging**
