### PR TITLE
fixed link

### PR DESCRIPTION
**Pull request by londoncalling**
Signed-off-by: Victoria Bialas <victoria.bialas@docker.com>

### CODE REVIEW

**Comment by londoncalling** [comment]
@jeffdm @icecrime @SvenDowideit Please have a look at this link fix and merge if okay. The link works now.

@SvenDowideit I know we discussed formatting links like this: 

`/docker-for-windows/#what-to-know-before-you-install`

but this does not appear to work in Docker for Mac and Windows. For example, see https://github.com/docker/toolbox/pull/516/files, which was originally formatted that way for that PR. 

If you look at the docs on the website now, these links in Mac toolbox install *are* working presumably because they have been changed to the format shown above: `/docker-for-windows/#what-to-know-before-you-install`

Let me know whether this makes sense. I'd like to go over link formatting with you again just to make sure I understand how we should be doing this.

**Comment by londoncalling** [comment]
@nathanleclaire @thaJeztah do either of you all have merge capabilities for Toolbox? 

I'd like to get this merged soon, since we are publishing a docs update today and this fixes what is currently a broken link. Could you take a look and merge if it looks good to you?

**Comment by thaJeztah** [comment]
hm, sorry, no, I don't have :cry:

**Comment by nathanleclaire** [comment]
I do but didn't see this in time.  Feel free to CC me in the future if more issues like this come up.  Thanks @londoncalling

**Comment by londoncalling** [comment]
No problem - thanks Nathan!

**Pull request merged**
