### PR TITLE
Upgrade git-for-windows to 2.7.0, and vbox to 5.0.14

### PR DESCRIPTION
**Pull request by SvenDowideit**
Signed-off-by: Sven Dowideit <SvenDowideit@home.org.au>

running a `make windows` failed on my windows box running toolbox - I'll increase the memory on the b2d vm and try again later some time.

### CODE REVIEW

**Comment by nathanleclaire** [comment]
Dang, new VBox?  Nice.

**Comment by nathanleclaire** [comment]
@jeffdm FYI

**Comment by nathanleclaire** [comment]
This LGTM

**Comment by nathanleclaire** [comment]
@dgageot @jeanlaurent WDYT

**Comment by dgageot** [comment]
LGTM

**Comment by jeffdm** [comment]
LGTM

**Pull request merged**
