### PR TITLE
Added powershell equivalents for start.sh and delete.sh

### PR DESCRIPTION
**Pull request by MartinSGill**

### CODE REVIEW

**Comment by jeffdm** [comment]
Hi there - thanks for the PR and sorry for the delay in getting back. What would be the best way for the user to access these scripts?

**Comment by MartinSGill** [comment]
They can either run the script directly from powershell, or if you want an equivalent to the "Docker Quickstart Terminal" for powershell, you can create a windows shortcut with:

```powershell -NoExit -File "C:\Program Files\Docker Toolbox\Start-DockerMachine.ps1"```

**Comment by jeffdm** [comment]
Got it, thanks! What's the advantage of this over calling the bash equivalents from Powershell? Is it that the user does not need to install Git Bash (which would make sense). Curious on the motives for this PR!

Sorry for the late follow up

**Comment by embray** [comment]
I was about to post and issue and/or PR for the same.  I can't speak to the OP's motivation but I can offer one.  I'm working on bundling Docker as part of a bundled application on Windows (in this case SageMath for Windows), and requiring Git + bash is just one more dependency / bit of overhead that seems unnecessary, and may only add further confusion to users who don't know what git is or why they need it.  In fact, if Git is deselected in the Docker Toolbox install, it still installs the "Docker Quickstart Terminal" shortcut, which is broken if Git is not installed (whether through Toolbox or independently).

I think for Windows the simpler approach is a native startup script rather than invoking an entire dependency that is not really technically needed given that `docker-machine env` can support Windows shells.

If some version of this PR is accepted this doc page should also be updated: https://docs.docker.com/windows/step_one/  In particular step 2 which states that bash is required.

**Comment by embray** [comment]
(As far as this PR is concerned the delete script can also be dropped since the `delete.sh` it's based on no longer exists.)

**Comment by somombo** [comment]
I have resolved this issue in a somewhat robust fashion. Please refer to PR https://github.com/docker/toolbox/pull/578 and Issue #579 

I look forward to your comments

**Pull request closed without merging**
