### PR TITLE
Unmounting /Users in the docker-machine, replacing it with a dynamic …

### PR DESCRIPTION
**Pull request by renedekat**
As the VBoxfs causes issues when updating files in mounted volumes, I've replaced it with an NFS mount. This makes it useful for development where you update files on your host machine and want to see the changes reflected immediately in a website.

I ran into issues when serving content through NGinx from a volume and updated the files. The changes were reflected locally and in the container, but not in the browser. With the NFS mount this is now solved.

The script uses the hostname and currently logged in user to create the NFS mount and update the /etc/exports file.

### CODE REVIEW

**Comment by nathanleclaire** [comment]
While I'd love to support this feature it would need to be more in depth than just this few lines of change to the startup script.  What happens to the export line when the VM IP changes?  Likewise, we would need a more robust way of mounting at start time than running `docker-machine ssh` through the quickstart.

**Comment by renedekat** [comment]
I know what you mean, and I am using a script with those 4 lines to update the mount, in case of an IP address change. If I had more time, I would investigate how this could be done in a better way or monitored, and updated dynamically.

Even if it won't be merged in it's current form, it might help someone else or it can be the start of a proper solution. I am open to suggestions to look further into the matter.

**Comment by nathanleclaire** [comment]
Yes, it's a decent start, I'd just be hesitant to merge anything in for NFS without very thorough planning and testing.  NFS can be really brittle (not that VBoxFS is much better in some cases).  For instance, I found that I have to have the following setting enabled for the NFS server on my Mac (in `/etc/nfs.conf`) to get this type of thing to work:

```
#
# nfs.conf: the NFS configuration file
#
nfs.server.mount.require_resv_port = 0
```

@jeffdm @mchiang0610 Do you think it's something we should support?  Enabling NFS for Mac users certainly would solve a lot of speed problems that

**Comment by renedekat** [comment]
Ah yes, I forgot I enabled that while testing other solutions.

I think the real solution should be added to the docker-machine package. Vagrant has an option to set the mount type to nfs with config.vm.synced_folder ".", "/vagrant", type: "nfs", so "borrowing" their code might be a solution.

**Comment by jeffdm** [comment]
Sorry for the delay, @renedekat 

While I do believe NFS provides many advantages, as @nathanleclaire mentioned, I think we'd need to incorporate much planning and testing (in `docker/machine`) before we can leverage that here in Toolbox. I'm going to close this in favor of continuing the discussion there, and I really appreciate your work on this - I know VirtualBox shared folders aren't always the best.

**Pull request closed without merging**
