### PR TITLE
Use NDIS5 host network filter drivers with VirtualBox

### PR DESCRIPTION
**Pull request by todorez**
VirtualBox 5.x+ includes both NDIS5 and NDIS6 host network filter drivers.
    NDIS6 is installed by default on Windows Vista and later. NDIS6 breaks
    host-only and bridge interfaces in VirtualBox. Please see the bug report
    below:
    
    https://www.virtualbox.org/ticket/14457

### CODE REVIEW

**Comment by jeffdm** [comment]
Hi there - thanks for the PR, and sorry for the long delay

What's the main advantage of using NDIS5?

**Comment by todorez** [comment]
The main advantage for using NDIS5 is that host-only interfaces can be created with VirtualBox reliably 100% of the time. When using NDIS6 with Windows 7, 8, 8.1 and 10 some hosts fail to start the boot2docker vm with the following error:

"Failed to open/create the internal network 'HostInterfaceNetworking-VirtualBox Host-Only Ethernet Adapter' (VERR_INTNET_FLT_IF_NOT_FOUND).

Failed to attach the network LUN (VERR_INTNET_FLT_IF_NOT_FOUND)."

Other people are experiencing this issue as well:
https://forums.virtualbox.org/viewtopic.php?f=6&t=70199 

Using NDIS5 by default in Docker Toolbox is not a bad idea until this bug gets fixed in VirtualBox.

**Comment by nathanleclaire** [comment]
I definitely think this merits a look, but I'm a bit confused.

I have been duping the "exit status on 1" type bug with VirtualBox on my Windows 10 VM but following the recommended suggestion to enable NDIS6 in the created Host-only interface http://superuser.com/questions/1002160/failed-to-start-virtual-device-in-oracle-virtual-box/1002243#1002243 seemed to fix it.  So, that seems to be the opposite of what is suggested here?

**Comment by nathanleclaire** [comment]
On this one, they're releasing a new version of VBox today which is supposed to fix some issues related to host-only networking, so let's see how that goes -- if symptoms continue to persist we'll think about making this the default.

**Comment by todorez** [comment]
The issue still persists with docker-toolbox 1.9.1g and VB 5.0.12

**Comment by nathanleclaire** [comment]
@jeffdm Any chance that we could get this as a checkbox in the Toolbox installer for Windows users?

**Comment by todorez** [comment]
@jeffdm @nathanleclaire I am closing this. 
Opened a new pull request (#404) which adds a checkbox to the installer to select NDIS5.

https://github.com/todorez/toolbox/commit/229eeb80914d70bb78d7c732c81d6941a0a88a35

**Pull request closed without merging**
