### PR TITLE
Remove the ability to modify the PATH because it has no benefits

### PR DESCRIPTION
**Pull request by AndreKR**

### CODE REVIEW

**Comment by AndreKR** [comment]
Created PR to remove that option:
https://github.com/docker/toolbox/pull/483

**Comment by jeffdm** [comment]
@AndreKR I think we still want the PATH to be modified in case they open their own shell separate from running `start.sh`

@nathanleclaire thoughts?

**Comment by AndreKR** [comment]
@jeffdm Please see [the issue](https://github.com/docker/toolbox/issues/484) that prompted me to implement this change. It seems that running docker from your own shell is not supported. (Or rather supporting it requires more work than just modifying the PATH.)

**Comment by lmmarsano** [comment]
AndreKR's solution is stabler, and respects multi-user systems with non-administrator accounts.
The status quo contaminates the global path environment of a single administrator account, and requires users to run as that administrator in order to work.
From the perspective of fundamental security, that's wrong.

**Pull request closed without merging**
