### PR TITLE
Fix quickstart terminal script for iTerm2

### PR DESCRIPTION
**Pull request by teknogeek**
The code in the script is

``` applescript
set itermRunning to (application "iTerm" is running)
set scriptPath to quoted form of POSIX path of ((path to me as text) & "::" & "start.sh")
set user_shell to do shell script "dscl /Search -read /Users/$USER UserShell | awk '{print $2}'"

tell application "iTerm"
    activate
    if not (exists window 1) or (itermRunning = false) then
        reopen
    else
        create window with profile "Default"
    end if
    tell current session of first window to write text "bash --login " & scriptPath
end tell
```

but I would recommend taking a look yourself anyways

### CODE REVIEW

**Comment by jeffdm** [comment]
Thanks for the PR! And sorry for the late reply. Does this work with all versions of iTerm (2.0+, including 2.9?)

**Comment by nathanleclaire** [comment]
Hm... We are vendoring binary executable files in this repo?  Where's the original source for this kept?

**Comment by jeffdm** [comment]
It is source, but you need to edit it with the AppleScript editor. I think there's a way to make it appear in GitHub.

**Comment by jeffdm** [comment]
Whoops, sorry for the close.

**Comment by teknogeek** [comment]
Yes you are :stuck_out_tongue: As for whether it works on all version of iTerm2, I can verify it works on my current version of iTerm2, `2.9.20160113`

**Comment by jeffdm** [comment]
@teknogeek thanks! Testing with older versions

**Pull request closed without merging**
