### PR TITLE
instructions for .scpt diff

### PR DESCRIPTION
**Pull request by virajkanwade**

### CODE REVIEW

**Comment by jeffdm** [comment]
Great! Thanks! I was wondering how this could be done.

- Could we put this in `Contributing.md`?
- Can you sign your commit?

**Comment by thaJeztah** [comment]
> Can you sign your commit?

Forgot there's no @GordonTheTurtle here; would that be helpful?

**Comment by jeffdm** [comment]
It definitely would!

**Comment by thaJeztah** [comment]
@jeffdm instructions can be found here; https://github.com/docker/leeroy, but if you need help setting up, Jess or David Calavera are the best persons to ask

**Comment by jeffdm** [comment]
@thaJeztah Awesome. Thanks!

**Comment by virajkanwade** [comment]
Was merged in #163

**Pull request closed without merging**
