### PR TITLE
Added support for iterm 3.0.0

### PR DESCRIPTION
**Pull request by virajkanwade**
Signed-off-by: Viraj Kanwade github@virajk.otherinbox.com

### CODE REVIEW

**Comment by virajkanwade** [comment]
@jeffdm supports both older and newer version of iterm

**Comment by bengro** [comment]
Nice one, worked! 

I had to create an iTerm profile called "Default" to make it work - I did not have a default profile to start with.

**Comment by tazeverywhere** [comment]
Perfect, thx a lot.

**Comment by bracketouverte** [comment]
Great work, just replaced the old one and it worked perfectly 👍

**Comment by razasayed** [comment]
Works great with iTerm2 v3.0.2 👍

**Comment by blindenvy** [comment]
Works for me on iTerm2 Build 3.0.2

**Comment by joshenders** [comment]
What is blocking this merge?

**Comment by jnials** [comment]
Yes please merge.

**Comment by ssbarnea** [comment]
Do we need to start an fundraising campaign to get this reviewed and merged? ;)

**Comment by abohne** [comment]
Sure would be nice if someone merged this.

**Comment by jaredgrubb** [comment]
Yes, please merge this! :)

**Comment by thaJeztah** [comment]
For reference; this is the content of the file

```applescript
set itermRunning to (application "iTerm" is running)
set scriptPath to quoted form of POSIX path of ((path to me as text) & "::" & "start.sh")
set user_shell to do shell script "dscl /Search -read /Users/$USER UserShell | awk '{print $2}'"

on theSplit(theString, theDelimiter)
	set oldDelimiters to AppleScript's text item delimiters
	set AppleScript's text item delimiters to theDelimiter
	set theArray to every text item of theString
	set AppleScript's text item delimiters to oldDelimiters
	return theArray
end theSplit

on IsModernVersion(version)
	set myArray to my theSplit(version, ".")
	set major to item 1 of myArray
	set minor to item 2 of myArray
	set veryMinor to item 3 of myArray
	
	if major < 2 then
		return false
	end if
	if major > 2 then
		return true
	end if
	if minor < 9 then
		return false
	end if
	if minor > 9 then
		return true
	end if
	if veryMinor < 20140903 then
		return false
	end if
	return true
end IsModernVersion

on NewLaunchTab()
	return "tell the current window to create tab with profile \"Default\""
end NewLaunchTab

on OldLaunchTab()
	return "tell the current terminal to launch session \"Default Session\""
end OldLaunchTab

on NewRunScript()
	return "tell the current window to tell the current session to write text "
end NewRunScript

on OldRunScript()
	# tell the current terminal to tell the current session to write text "bash --login " & scriptPath
	return "tell the current terminal to tell the current session to write text "
end OldRunScript

tell application "iTerm"
	# activate
	set launchTab to ""
	if not (exists window 1) or (itermRunning = false) then
		reopen
	else
		if my IsModernVersion(version) then
			set launchTab to my NewLaunchTab()
		else
			set launchTab to my OldLaunchTab()
		end if
	end if
	if my IsModernVersion(version) then
		set runScript to my NewRunScript()
	else
		set runScript to my OldRunScript()
	end if
end tell

set fullScript to "tell application \"iTerm\"
" & launchTab & "
" & runScript & " \"bash --login " & scriptPath & "\"
end tell"

log fullScript
run script fullScript
```

**Comment by internalsystemerror** [comment]
so ... whats the hold up?

**Comment by ssbarnea** [comment]
@internalsystemerror I think that the Docker team is still looking for a way to implement this as a breaking change. ;)


I missed the birthday celebration of this one year old PR, really... agile.

**Comment by AshleyAitken** [comment]
Please merge

**Comment by teknogeek** [comment]
Why hasn't this been merged yet?

**Comment by cyberscribe** [comment]
Please merge and release

**Comment by FrenchBen** [comment]
Thanks @thaJeztah for the help

**Comment by internalsystemerror** [comment]
@FrenchBen tx for the merge!

**Pull request merged**
